[features]
seeds = false
skip-lint = false

[programs.localnet]
simple_perp_dex = "PerpDex1111111111111111111111111111111111"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
